dist: trusty
sudo: required

# we disable the new recursive submodule initialization
# (https://github.com/travis-ci/travis-ci/issues/4099)
# because we don't need the recursive submodules and some would fail
# due to ssh urls
git:
  submodules: false

# default is ruby, we set python in case we need to do some
# advanced scripting in our setup of the C++ tests
language: python

matrix:
  include:
    - os: linux
      services: docker
      env: docker_img=gsauthof/fedora-cxx-devel:25 CMAKE_BUILD_TYPE=Debug CXXFLAGS="--coverage -fsanitize=address -fsanitize=undefined" targets="ut imapdl" UT_PREFIX=/srv/src
      python: 3.5

before_install:
  - git submodule update --init # cf. above `git:` section
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_install.sh

install:
  - docker exec --user root devel dnf -y install botan-devel
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/install.sh

before_script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_script.sh

script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/script.sh

after_success:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/after_success.sh
